### ISSUE TITLE
Fix for #6578 Breaks Carts for New Customers

### ISSUE THREAD

**Issue by stephenhmarsh** [spree/spree_auth_devise#290]
(At least in *our* integration tests): https://github.com/spree/spree_auth_devise/commit/336b0e4f3a9c38dba36c8deef37549f48f61672f  breaks cart 'merging' when users try to register.  In other words, if you're a new customer and create an account your entire cart is dumped when you register, including the checkout stages.

**Comment by JDutil** [comment]
Please provide the information requested here https://github.com/spree/spree/blob/master/CONTRIBUTING.md#filing-an-issue to help people troubleshoot your issue.

**Comment by stephenhmarsh** [comment]
Hi Jeff,
Consider this a friendly bug report.  If this is not specific to our implementation (admittedly we have hacked on all these gems), then any release with this commit has this problem because you now call `associate_user!` on orders where the email == user's email.   By nature this would exclude the cart they had going into new user registration.

**Comment by dangerdogz** [comment]
1) Login
2) Add item to cart
3) Logout
4) Add item to cart
5) Login

Expected results : 

I expect my "guest cart" to be merged with my last "signed in" cart. Instead, you're left only with the "signed in" cart

Gemfile
https://gist.github.com/dangerdogz/5563861ca6a1d4d0649f

Gemfile.lock
https://gist.github.com/dangerdogz/bf19cf07bf569360afd8

The commit who introduced the issue 336b0e4

It is a serious regression since it breaks a widely used workflow : shop offline, log in before checkout to 

I believe the original problem referenced above could be better solved in the following ways : 

1) In the offending code (warden.rb), add a check to avoid associating already completed orders

```ruby
Warden::Manager.after_set_user except: :fetch do |user, auth, opts|
  if auth.cookies.signed[:guest_token].present?
    if user.is_a?(Spree::User)
      Spree::Order.where(email: user.email, guest_token: auth.cookies.signed[:guest_token], user_id: nil).each do |order|
        order.associate_user!(user) unless order.completed?
      end
    end
  end
end
```

2) Since the guest_token is only deleted on checkout, it's somewhat dangerous with guest checkout, so after a guest checkout we could clear the session[:guest_token] since from all standpoints, the guest session is completed, so you can start with a clean slate after that

**Comment by vascosantos** [comment]
We had to revert to the old code.
All items added to the shopping cart before the user signs in were being completely discarded.

Luckily for us, we don't allow guest checkout, so we're fine with the old code.
